### ISSUE TITLE
Local development configuration with Serverless offline plugin

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/calasasaya#3]
Install the serverless-offline plugin and add the plugin for doing local development with a local DynamoDB emulator.

**Comment by timofeysie** [comment]
$ serverless invoke local --log
...
ServerlessError: This command requires the --function option / -f shortcut. Usage: Name of the function
    at _.forEach (/Users/tim/.nvm/versions/node/v10.14.2/lib/node_modules/serverless/lib/classes/PluginManager.js:492:15)
    at /Users/tim/.nvm/versions/node/v10.14.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:4911:15
